spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=Store
    username: sa
    password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    tomcat:
      max-swallow-size: 100MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 禁止大写变小写时自动添加下划线
server:
  port: 9090