spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=Store
    username: sa
    password: 123456
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    tomcat:
      max-swallow-size: 100MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 禁止大写变小写时自动添加下划线 #先打开试试
server:
  port: 9090
alipay:
  appId: 2021000121653006
  appPrivateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDAEZ3wtfQpxsZELOaDHUQB+Nwk5SV/hogg5gYliCkvRO5fZwfwhI+txQHhAxaK3CnoxD6WnZ/RanPvzkjrOrgX/5c/QbeBo3j+HBPAGnnOSUv+kRH1Cb3RY+hnb/R5QhGa54MzoA2sT0YWuSnxE+3RX+Uccqjs91kYUPUeWrGm13MRaELqvqU/HTpfvDwFK+PNep30RST2zkCZPGbo3528RwKMBPW7gF9qhw63hfklxf0lnThWWDgrXJa3WNZ0cYDmngKmu06QU1bW3UG02EcE+s+6P5J1GSAZJrqNG2N62YF8fiC5DkgkuZahzzkQyPwl1ywmdfrYtmy8rBJdqjiRAgMBAAECggEAeg3371LBkZbGweZCqkl7wUETLMMNnEey1C049LrdaTOFw8ymp/qlj4jlU8dxmNamL0wedfo+6IacnGTbw9gxytZamBE7+z8WEW1oQ6jPhP7hMymfXrdND/ZMZwcnNbN9mpHKt5Dbf4d1A9WxSIkglPA6mWRn4wagcKppyltaD6o37sn8KyrqZNQUh5dE6m0+s73pObPoKHikQZVjnO+0h5+lNhJj2cBN/fXSjNwOFOc3HrG+KL8Sr4k7WGp8Jf2nmQEJnt3NzclYjWDp/cnRN+zbsnPNfmU6D/TzfSTftVuHHcbyP8dBay1XIpfLesLV0zJgyeOVvm4NdfvFj6wwEQKBgQD+c3ndy4JtKpS8oHjZaUSTQassk/Ei76iMJD228LYkMC7kJD1ItgLTWVK2FGEoH9SRhawS8l/v4silMiGl2WQP+Z15TV3UkyF6n4iWghgzMFGXsr/0uNq9zHcy1JZWgkK0l38HheDkVXWV2j5wL0q5/kSeJ6y8/uhb4SFEc5XQVQKBgQDBPO1vtL7sXtJbN0IUNQct67RRGe1IIYmDieDJowgYIQ6hBDiYTKPNBqnnEBzDsNsWrNbJ/tCk/MGiU2urLAWxQVVr4BJmeaNLBZl02WNIpxGoM8JfMHu6LK29GZIoIf4+YHG+f3gz3gacrXwU2/iqCXnbRC0Zq4hGTGwnDdNTTQKBgQD5wNDCcknf6ya5Cu3zwI6t14wzojbS6tfOTphA4350gNLV3fhFUVnup0M3M0O2BaA5AjLHGh4usLPu6gj66Cl+QK1f7h+GUrBO0x5XVPR58hh0ROCDTZpvJ61sOBwkZ5Ef/3+RG8iFdpiG8QPOS60WaMxjTGAR1kauQIjNzoIjTQKBgQC9/FstQrWby7Zh/Dg5idFfMqh8PFNwYZjD/OFHHcUthALQCEhkZKV/RJfzF4JQXCdrac9ble4o6GCwafgnuQZ3udZ0Uz+EBP+pGP5BRiI5IhlYGFt4H0DmUFsY2nU6hAFl7oimVMknpZk2ndKq54LaGqr2C1eUL3OyOhzzYMJu2QKBgQCa0a1iHp9nVrheFtXZX5CQe/YZTpxwiEeMOTetvaudHImm+JgQgKZ5RZvAgtijTG/C5xkBzVJNj6MT9C/RYX6V4QcOMkQkGSuvp/OuTMuED8Qo/n5hauuVGxmI8KeQC49PRJhsNVbszN/zfrvCUn9FyKw585MU1zAdgv+Hosu+0Q==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA22kkEFvgl0pSuzG/Z2QbYljzpYbRevUBv2nVqRqISa5NyVb+fidvzsH8vKYL7rr5odoikSVWnFoAiBy2KHMdglDSUDJrbZbF8ahCjK2e2UAqbSTgiHgFG07SDdWbpNdeG9E1z6EyPpkdTdVcfHbr1MR0wFRZw4SeR/0Bejeej1WY34L+QRXaAQRo4YGnCM4GHvEXJXrJyd3MrClY3Nxhi/7Z3U+Sq41YRGMdE3gK5UoZhW9LbaD5P7wMukw7bPhWVjhklf21G3QpMvqmAjAhxbXYQsgjFYcDTLcE10Ouy5DansCC3imUuXpokgUBqI32MVvGhxAXf9KJOY5b52qCDQIDAQAB
  notifyUrl: http://ts8dwi.natappfree.cc/alipay/notify